# Trade Execution

Runs execution strategies against the 5-minute `BINNED_DATA` bins and analyses the results (fill rate, implementation shortfall, cost).

All reusable logic lives in [`execution.py`](execution.py); this notebook is the driver. (`test_snowflake.ipynb` stays the data explorer.)

**Layers** (see `execution.py` docstrings for full detail):

| Function | What it does |
|---|---|
| `simulate_bin_fill` | scalar reference model for a single bin |
| `twap_schedule` | baseline strategy: split quantity evenly across the day's bins |
| `vwap_schedule` | baseline strategy: split quantity by each bin's share of the day's volume |
| `run_strategy` | run one order `(security, date, side, quantity)` → per-bin fills |
| `run_trade_list` | run many orders (the trade list) → per-bin fills with `order_id` |
| `summarise_fills` | collapse to one row per order with fill rate / IS / cost |

In [ ]:
import polars as pl
from execution import (
    twap_schedule,
    vwap_schedule,
    run_strategy,
    run_trade_list,
    summarise_fills,
)

pl.Config.set_tbl_cols(-1)
RAW = "data/raw"

trade_list = pl.read_csv(f"{RAW}/trade_list.csv")
trade_list.head()

## Load bins

For a quick demo we load bins for just a couple of instruments (one liquid, one illiquid). For a full back-test, read the whole table instead — it is ~13M rows / ~2.5 GB in memory:

```python
bins = pl.read_csv(f"{RAW}/binned_data.csv")
```

In [29]:
demo_secs = ["GC2025V Comdty", "PA2022Z Comdty"]  # liquid gold, illiquid palladium

bins = (
    pl.scan_csv(f"{RAW}/binned_data.csv")
    .filter(pl.col("security").is_in(demo_secs))
    .collect()
)
bins

shape: (16_929, 25)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ qco ┆ pub ┆ sec ┆ bin ┆ gmt ┆ ope ┆ hig ┆ low ┆ clo ┆ twa ┆ twa ┆ bid ┆ bid ┆ ask ┆ ask ┆ vol ┆ sig ┆ tra ┆ vwa ┆ twa ┆ twa ┆ bid ┆ bid ┆ ask ┆ ask │
│ de  ┆ lic ┆ uri ┆ _st ┆ _of ┆ n   ┆ h   ┆ --- ┆ se  ┆ _bi ┆ _as ┆ _si ┆ _si ┆ _si ┆ _si ┆ ume ┆ ned ┆ de_ ┆ p   ┆ _bi ┆ _as ┆ _st ┆ _en ┆ _st ┆ _en │
│ --- ┆ ati ┆ ty  ┆ art ┆ fse ┆ --- ┆ --- ┆ f64 ┆ --- ┆ d_s ┆ k_s ┆ ze_ ┆ ze_ ┆ ze_ ┆ ze_ ┆ --- ┆ _vo ┆ cou ┆ --- ┆ d   ┆ k   ┆ art ┆ d   ┆ art ┆ d   │
│ str ┆ on_ ┆ --- ┆ _ti ┆ t_h ┆ f64 ┆ f64 ┆     ┆ f64 ┆ ize ┆ ize ┆ sta ┆ end ┆ sta ┆ end ┆ i64 ┆ lum ┆ nt  ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│     ┆ dat ┆ str ┆ me  ┆ our ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ rt  ┆ --- ┆ rt  ┆ --- ┆     ┆ e   ┆ --- ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 │
│     ┆ e   ┆     ┆ --- ┆ s   ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ i64 ┆ --- ┆ i64 ┆     ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ --- ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ i64 ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ GC  ┆ 202 ┆ GC2 ┆ 12: ┆ -4. ┆ 335 ┆ 335 ┆ 335 ┆ 335 ┆ 3.7 ┆ 4.4 ┆ 7   ┆ 2   ┆ 4   ┆ 1   ┆ 5   ┆ 3   ┆ 5   ┆ 335 ┆ 335 ┆ 335 ┆ 335 ┆ 335 ┆ 335 ┆ 335 │
│     ┆ 5-0 ┆ 025 ┆ 30: ┆ 0   ┆ 7.0 ┆ 7.2 ┆ 6.9 ┆ 7.1 ┆ 232 ┆ 169 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7.0 ┆ 7.1 ┆ 7.4 ┆ 7.4 ┆ 7.0 ┆ 7.8 ┆ 7.2 │
│     ┆ 8-2 ┆ V   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 47  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 066 ┆ 287 ┆     ┆     ┆     ┆     │
│     ┆ 1   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 62  ┆ 51  ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ GC  ┆ 202 ┆ GC2 ┆ 13: ┆ -4. ┆ 335 ┆ 335 ┆ 335 ┆ 335 ┆ 3.7 ┆ 4.0 ┆ 2   ┆ 4   ┆ 5   ┆ 4   ┆ 2   ┆ -1  ┆ 2   ┆ 335 ┆ 335 ┆ 335 ┆ 335 ┆ 335 ┆ 335 ┆ 335 │
│     ┆ 5-0 ┆ 025 ┆ 05: ┆ 0   ┆ 8.0 ┆ 8.3 ┆ 8.0 ┆ 8.3 ┆ 695 ┆ 407 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8.1 ┆ 8.1 ┆ 8.4 ┆ 7.5 ┆ 7.9 ┆ 7.7 ┆ 8.2 │
│     ┆ 8-2 ┆ V   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 27  ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 664 ┆ 343 ┆     ┆     ┆     ┆     │
│     ┆ 1   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 69  ┆ 43  ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ GC  ┆ 202 ┆ GC2 ┆ 07: ┆ -4. ┆ 374 ┆ 374 ┆ 374 ┆ 374 ┆ 3.5 ┆ 3.6 ┆ 3   ┆ 2   ┆ 5   ┆ 6   ┆ 12  ┆ 7   ┆ 12  ┆ 374 ┆ 374 ┆ 374 ┆ 374 ┆ 374 ┆ 374 ┆ 374 │
│     ┆ 5-0 ┆ 025 ┆ 15: ┆ 0   ┆ 3.7 ┆ 5.3 ┆ 3.3 ┆ 5.3 ┆ 859 ┆ 399 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3.9 ┆ 4.4 ┆ 4.7 ┆ 3.4 ┆ 6.2 ┆ 3.7 ┆ 6.5 │
│     ┆ 9-2 ┆ V   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 83  ┆ 73  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 333 ┆ 857 ┆ 808 ┆     ┆     ┆     ┆     │
│     ┆ 6   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆ 34  ┆ 58  ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ GC  ┆ 202 ┆ GC2 ┆ 07: ┆ -4. ┆ 357 ┆ 357 ┆ 357 ┆ 357 ┆ 3.8 ┆ 3.6 ┆ 8   ┆ 2   ┆ 2   ┆ 1   ┆ 15  ┆ 2   ┆ 11  ┆ 357 ┆ 357 ┆ 357 ┆ 357 ┆ 357 ┆ 357 ┆ 357 │
│     ┆ 5-0 ┆ 025 ┆ 30: ┆ 0   ┆ 6.6 ┆ 6.6 ┆ 5.6 ┆ 5.8 ┆ 002 ┆ 240 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6.0 ┆ 5.9 ┆ 6.2 ┆ 6.3 ┆ 5.8 ┆ 6.6 ┆ 6.0 │
│     ┆ 9-0 ┆ V   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ 47  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 333 ┆ 997 ┆ 456 ┆     ┆     ┆     ┆     │
│     ┆ 5   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆ 61  ┆ 9   ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ GC  ┆ 202 ┆ GC2 ┆ 14: ┆ -4. ┆ 362 ┆ 362 ┆ 361 ┆ 361 ┆ 3.1 ┆ 3.6 ┆ 2   ┆ 7   ┆ 2   ┆ 6   ┆ 7   ┆ 2   ┆ 7   ┆ 362 ┆ 362 ┆ 362 ┆ 362 ┆ 361 ┆ 362 ┆ 361 │
│     ┆ 5-0 ┆ 025 ┆ 10: ┆ 0   ┆ 1.0 ┆ 1.0 ┆ 9.2 ┆ 9.2 ┆ 539 ┆ 740 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆ 1.0 ┆ 1.2 ┆ 2.2 ┆ 9.0 ┆ 2.4 ┆ 9.3 │
│     ┆ 9-0 ┆ V   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 97  ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 714 ┆ 391 ┆ 650 ┆     ┆     ┆     ┆     │
│     ┆ 5   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 29  ┆ 2   ┆ 13  ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ PA  ┆ 202 ┆ PA2 ┆ 04: ┆ -4. ┆ 199 ┆ 200 ┆ 198 ┆ 199 ┆ 1.2 ┆ 1.5 ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 17  ┆ 2   ┆ 15  ┆ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 199 │
│     ┆ 2-1 ┆ 022 ┆ 10: ┆ 0   ┆ 8.0 ┆ 1.0 ┆ 7.5 ┆ 5.0 ┆ 560 ┆ 950 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6.9 ┆ 3.8 ┆ 8.5 ┆ 1.0 ┆ 2.5 ┆ 6.0 ┆ 7.0 │
│     ┆ 0-2 ┆ Z   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 73  ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 411 ┆ 737 ┆ 296 ┆     ┆     ┆     ┆     │
│     ┆ 0   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆ 82  ┆ 93  ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ PA  ┆ 202 ┆ PA2 ┆ 04: ┆ -4. ┆ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 1.2 ┆ 2.1 ┆ 1   ┆ 1   ┆ 1   ┆ 9   ┆ 1   ┆ 0   ┆ 1   ┆ 199 ┆ 198 ┆ 199 ┆ 198 ┆ 199 ┆ 199 ┆ 199 │
│     ┆ 2-1 ┆ 022 ┆ 30: ┆ 0   ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 2.0 ┆ 014 ┆ 444 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2.0 ┆ 9.4 ┆ 3.6 ┆ 7.5 ┆ 1.5 ┆ 2.0 ┆ 6.0 │
│     ┆ 0-2 ┆ Z   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 563 ┆ 603 ┆     ┆     ┆     ┆     │
│     ┆ 0   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 87  ┆ 9   ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ PA  ┆ 202 ┆ PA2 ┆ 15: ┆ -4. ┆ 215 ┆ 215 ┆ 215 ┆ 215 ┆ 1.1 ┆ 1.6 ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 6   ┆ 2   ┆ 4   ┆ 215 ┆ 215 ┆ 215 ┆ 215 ┆ 215 ┆ 215 ┆ 215 │
│     ┆ 2-0 ┆ 022 ┆ 40: ┆ 0   ┆ 6.0 ┆ 8.0 ┆ 5.5 ┆ 6.5 ┆ 267 ┆ 347 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6.2 ┆ 4.5 ┆ 7.6 ┆ 4.5 ┆ 4.0 ┆ 7.5 ┆ 8.5 │
│     ┆ 9-2 ┆ Z   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 73  ┆ 57  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 044 ┆ 818 ┆     ┆     ┆     ┆     │
│     ┆ 8   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 05  ┆ 5   ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ PA  ┆ 202 ┆ PA2 ┆ 08: ┆ -4. ┆ 228 ┆ 229 ┆ 227 ┆ 227 ┆ 1.3 ┆ 1.1 ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆ 24  ┆ -3  ┆ 21  ┆ 228 ┆ 228 ┆ 228 ┆ 228 ┆ 227 ┆ 228 ┆ 228 │
│     ┆ 2-1 ┆ 022 ┆ 20: ┆ 0   ┆ 6.0 ┆ 0.5 ┆ 9.5 ┆ 9.5 ┆ 717 ┆ 943 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5.4 ┆ 2.9 ┆ 7.8 ┆ 1.0 ┆ 9.5 ┆ 6.0 ┆ 4.0 │
│     ┆ 0-0 ┆ Z   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 17  ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 791 ┆ 77  ┆ 621 ┆     ┆     ┆     ┆     │
│     ┆ 5   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 67  ┆     ┆ 73  ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ PA  ┆ 202 ┆ PA2 ┆ 03: ┆ -5. ┆ 186 ┆ 186 ┆ 186 ┆ 186 ┆ 1.0 ┆ 1.8 ┆ 2   ┆ 1   ┆ 1   ┆ 3   ┆ 0   ┆ 0   ┆ 0   ┆ nul ┆ 186 ┆ 186 ┆ 186 ┆ 186 ┆ 187 ┆ 186 │
│     ┆ 2-1 ┆ 022 ┆ 10: ┆ 0   ┆ 7.5 ┆ 7.5 ┆ 7.5 ┆ 7.5 ┆ 737 ┆ 481 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ 2.0 ┆ 9.7 ┆ 2.5 ┆ 2.0 ┆ 0.5 ┆ 9.0 │
│     ┆ 1-1 ┆ Z   ┆ 00. ┆     ┆     ┆     ┆     ┆     ┆ 07  ┆ 97  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 881 ┆ 060 ┆     ┆     ┆     ┆     │
│     ┆ 0   ┆ Com ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 98  ┆ 5   ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

## Single order

Take one real row from the trade list (one bucket for a security-day) and run it. `run_strategy` takes the bins for that `(security, date)` plus the row's `side` and `quantity`, and returns one row per bin.

In [30]:
# pick one real order from the trade list (one row = one bucket for a security-day)
order = trade_list.filter(pl.col("security") == "GC2025V Comdty").row(0, named=True)
print(order)

day = bins.filter(
    (pl.col("security") == order["security"])
    & (pl.col("publication_date") == order["date"])
)

fills = run_strategy(day, side=order["side"], quantity=order["quantity"], strategy=twap_schedule)
fills.head()

{'security': 'GC2025V Comdty', 'date': '2025-07-31', 'trade_list': 'large_buys', 'side': 'buy', 'quantity': 761}

shape: (5, 22)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ord ┆ sec ┆ pub ┆ qco ┆ sid ┆ ord ┆ bin ┆ vol ┆ vwa ┆ twa ┆ twa ┆ spr ┆ q_r ┆ q_f ┆ q_u ┆ par ┆ sli ┆ fil ┆ not ┆ cos ┆ fil ┆ dat │
│ er_ ┆ uri ┆ lic ┆ de  ┆ e   ┆ er_ ┆ _st ┆ ume ┆ p   ┆ _bi ┆ _as ┆ ead ┆ equ ┆ ill ┆ nfi ┆ tic ┆ ppa ┆ l_p ┆ ion ┆ t   ┆ led ┆ a_a │
│ id  ┆ ty  ┆ ati ┆ --- ┆ --- ┆ qua ┆ art ┆ --- ┆ --- ┆ d   ┆ k   ┆ --- ┆ est ┆ ed  ┆ lle ┆ ipa ┆ ge_ ┆ ric ┆ al  ┆ --- ┆ --- ┆ vai │
│ --- ┆ --- ┆ on_ ┆ str ┆ str ┆ nti ┆ _ti ┆ i64 ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ ed  ┆ --- ┆ d   ┆ tio ┆ fac ┆ e   ┆ --- ┆ f64 ┆ boo ┆ lab │
│ i32 ┆ str ┆ dat ┆     ┆     ┆ ty  ┆ me  ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ --- ┆ n_r ┆ tor ┆ --- ┆ f64 ┆     ┆ l   ┆ le  │
│     ┆     ┆ e   ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ ate ┆ --- ┆ f64 ┆     ┆     ┆     ┆ --- │
│     ┆     ┆ --- ┆     ┆     ┆ f64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆ boo │
│     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ l   │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 761 ┆ 03: ┆ 23  ┆ 332 ┆ 332 ┆ 332 ┆ 0.2 ┆ 4.8 ┆ 4.8 ┆ 0.0 ┆ 0.2 ┆ 0.2 ┆ 332 ┆ 161 ┆ 0.3 ┆ tru ┆ tru │
│     ┆ 025 ┆ 5-0 ┆     ┆     ┆ .0  ┆ 00: ┆     ┆ 3.4 ┆ 2.7 ┆ 3.0 ┆ 890 ┆ 471 ┆ 471 ┆     ┆ 107 ┆ 298 ┆ 3.4 ┆ 09. ┆ 219 ┆ e   ┆ e   │
│     ┆ V   ┆ 7-3 ┆     ┆     ┆     ┆ 00. ┆     ┆ 217 ┆ 994 ┆ 885 ┆ 15  ┆ 34  ┆ 34  ┆     ┆ 45  ┆ 25  ┆ 881 ┆ 391 ┆ 6   ┆     ┆     │
│     ┆ Com ┆ 1   ┆     ┆     ┆     ┆ 000 ┆     ┆ 39  ┆ 93  ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 62  ┆ 664 ┆     ┆     ┆     │
│     ┆ dty ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 761 ┆ 03: ┆ 233 ┆ 332 ┆ 332 ┆ 332 ┆ 0.2 ┆ 4.8 ┆ 4.8 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 332 ┆ 161 ┆ 0.1 ┆ tru ┆ tru │
│     ┆ 025 ┆ 5-0 ┆     ┆     ┆ .0  ┆ 05: ┆     ┆ 4.7 ┆ 3.6 ┆ 3.9 ┆ 784 ┆ 471 ┆ 471 ┆     ┆ 208 ┆ 407 ┆ 4.7 ┆ 15. ┆ 900 ┆ e   ┆ e   │
│     ┆ V   ┆ 7-3 ┆     ┆     ┆     ┆ 00. ┆     ┆ 274 ┆ 839 ┆ 623 ┆ 5   ┆ 34  ┆ 34  ┆     ┆ 03  ┆ 89  ┆ 666 ┆ 588 ┆ 21  ┆     ┆     │
│     ┆ Com ┆ 1   ┆     ┆     ┆     ┆ 000 ┆     ┆ 68  ┆ 17  ┆ 68  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 71  ┆ 766 ┆     ┆     ┆     │
│     ┆ dty ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 761 ┆ 03: ┆ 165 ┆ 332 ┆ 332 ┆ 332 ┆ 0.2 ┆ 4.8 ┆ 4.8 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 332 ┆ 161 ┆ 0.2 ┆ tru ┆ tru │
│     ┆ 025 ┆ 5-0 ┆     ┆     ┆ .0  ┆ 10: ┆     ┆ 4.7 ┆ 4.3 ┆ 4.6 ┆ 897 ┆ 471 ┆ 471 ┆     ┆ 293 ┆ 484 ┆ 4.8 ┆ 15. ┆ 085 ┆ e   ┆ e   │
│     ┆ V   ┆ 7-3 ┆     ┆     ┆     ┆ 00. ┆     ┆ 848 ┆ 710 ┆ 607 ┆ 38  ┆ 34  ┆ 34  ┆     ┆ 77  ┆ 71  ┆ 278 ┆ 885 ┆ 12  ┆     ┆     │
│     ┆ Com ┆ 1   ┆     ┆     ┆     ┆ 000 ┆     ┆ 48  ┆ 42  ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66  ┆ 389 ┆     ┆     ┆     │
│     ┆ dty ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 761 ┆ 03: ┆ 19  ┆ 332 ┆ 332 ┆ 332 ┆ 0.3 ┆ 4.8 ┆ 4.8 ┆ 0.0 ┆ 0.2 ┆ 0.2 ┆ 332 ┆ 161 ┆ 0.4 ┆ tru ┆ tru │
│     ┆ 025 ┆ 5-0 ┆     ┆     ┆ .0  ┆ 15: ┆     ┆ 3.7 ┆ 3.9 ┆ 4.2 ┆ 493 ┆ 471 ┆ 471 ┆     ┆ 551 ┆ 428 ┆ 3.8 ┆ 11. ┆ 112 ┆ e   ┆ e   │
│     ┆ V   ┆ 7-3 ┆     ┆     ┆     ┆ 00. ┆     ┆ 526 ┆ 401 ┆ 895 ┆ 97  ┆ 34  ┆ 34  ┆     ┆ 12  ┆ 38  ┆ 374 ┆ 084 ┆ 64  ┆     ┆     │
│     ┆ Com ┆ 1   ┆     ┆     ┆     ┆ 000 ┆     ┆ 32  ┆ 78  ┆ 75  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 79  ┆ 848 ┆     ┆     ┆     │
│     ┆ dty ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 761 ┆ 03: ┆ 36  ┆ 332 ┆ 332 ┆ 332 ┆ 0.3 ┆ 4.8 ┆ 4.8 ┆ 0.0 ┆ 0.1 ┆ 0.2 ┆ 332 ┆ 161 ┆ 0.3 ┆ tru ┆ tru │
│     ┆ 025 ┆ 5-0 ┆     ┆     ┆ .0  ┆ 20: ┆     ┆ 5.4 ┆ 5.5 ┆ 5.9 ┆ 074 ┆ 471 ┆ 471 ┆     ┆ 346 ┆ 037 ┆ 5.5 ┆ 19. ┆ 036 ┆ e   ┆ e   │
│     ┆ V   ┆ 7-3 ┆     ┆     ┆     ┆ 00. ┆     ┆ 833 ┆ 931 ┆ 006 ┆ 44  ┆ 34  ┆ 34  ┆     ┆ 43  ┆ 7   ┆ 459 ┆ 366 ┆ 62  ┆     ┆     │
│     ┆ Com ┆ 1   ┆     ┆     ┆     ┆ 000 ┆     ┆ 33  ┆ 79  ┆ 23  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 81  ┆ 189 ┆     ┆     ┆     │
│     ┆ dty ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [31]:
summarise_fills(fills)

shape: (1, 23)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ord ┆ sec ┆ dat ┆ qco ┆ sid ┆ ord ┆ n_b ┆ n_f ┆ n_f ┆ tot ┆ tot ┆ tot ┆ fil ┆ tot ┆ arr ┆ ter ┆ fil ┆ avg ┆ unf ┆ par ┆ exe ┆ is_ ┆ is_ │
│ er_ ┆ uri ┆ e   ┆ de  ┆ e   ┆ er_ ┆ ins ┆ ill ┆ ill ┆ al_ ┆ al_ ┆ al_ ┆ led ┆ al_ ┆ iva ┆ min ┆ l_r ┆ _fi ┆ ill ┆ tic ┆ c_s ┆ cur ┆ bps │
│ id  ┆ ty  ┆ --- ┆ --- ┆ --- ┆ qua ┆ --- ┆ abl ┆ ed  ┆ vol ┆ req ┆ fil ┆ _no ┆ cos ┆ l_p ┆ al_ ┆ ate ┆ ll_ ┆ ed_ ┆ ipa ┆ lip ┆ ren ┆ --- │
│ --- ┆ --- ┆ str ┆ str ┆ str ┆ nti ┆ u32 ┆ e   ┆ --- ┆ ume ┆ ues ┆ led ┆ tio ┆ t   ┆ ric ┆ pri ┆ --- ┆ pri ┆ qty ┆ tio ┆ pag ┆ cy  ┆ f64 │
│ i32 ┆ str ┆     ┆     ┆     ┆ ty  ┆     ┆ --- ┆ u32 ┆ --- ┆ ted ┆ --- ┆ nal ┆ --- ┆ e   ┆ ce  ┆ f64 ┆ ce  ┆ --- ┆ n_o ┆ e_b ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ u32 ┆     ┆ i64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆     ┆ --- ┆ f64 ┆ ver ┆ ps  ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆     ┆ all ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 761 ┆ 157 ┆ 156 ┆ 156 ┆ 797 ┆ 761 ┆ 750 ┆ 2.4 ┆ 48. ┆ 332 ┆ 331 ┆ 0.9 ┆ 332 ┆ 10. ┆ 0.0 ┆ 7.5 ┆ 182 ┆ 7.2 │
│     ┆ 025 ┆ 5-0 ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆ 3   ┆ .0  ┆ .76 ┆ 970 ┆ 263 ┆ 3.4 ┆ 6.9 ┆ 865 ┆ 5.9 ┆ 235 ┆ 941 ┆ 831 ┆ 6.1 ┆ 206 │
│     ┆ V   ┆ 7-3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 433 ┆ e6  ┆ 654 ┆ 217 ┆ 846 ┆ 5   ┆ 419 ┆ 669 ┆ 63  ┆ 5   ┆ 883 ┆ 36  │
│     ┆ Com ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ 39  ┆ 15  ┆     ┆ 4   ┆     ┆     ┆     ┆ 11  ┆     │
│     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

## Run the trade list

The `TRADE_LIST` table has six rows per (security, date) — `small_buys`, `small_sells`, `medium_buys`, `medium_sells`, `large_buys`, `large_sells`. Pass `trade_list=` to run **one bucket at a time** (the usual back-test). Each order gets a unique `order_id` and is auto-tagged with its bucket.

In [32]:
orders = trade_list.filter(pl.col("security").is_in(demo_secs))

# run a single bucket, e.g. medium_buys (one of the six)
all_fills = run_trade_list(bins, orders, trade_list="medium_buys", strategy=twap_schedule)
all_fills.shape

(16929, 23)

In [33]:
summary = summarise_fills(all_fills)
summary.sort("security", "side")

shape: (108, 24)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ord ┆ tra ┆ sec ┆ dat ┆ qco ┆ sid ┆ ord ┆ n_b ┆ n_f ┆ n_f ┆ tot ┆ tot ┆ tot ┆ fil ┆ tot ┆ arr ┆ ter ┆ fil ┆ avg ┆ unf ┆ par ┆ exe ┆ is_ ┆ is_ │
│ er_ ┆ de_ ┆ uri ┆ e   ┆ de  ┆ e   ┆ er_ ┆ ins ┆ ill ┆ ill ┆ al_ ┆ al_ ┆ al_ ┆ led ┆ al_ ┆ iva ┆ min ┆ l_r ┆ _fi ┆ ill ┆ tic ┆ c_s ┆ cur ┆ bps │
│ id  ┆ lis ┆ ty  ┆ --- ┆ --- ┆ --- ┆ qua ┆ --- ┆ abl ┆ ed  ┆ vol ┆ req ┆ fil ┆ _no ┆ cos ┆ l_p ┆ al_ ┆ ate ┆ ll_ ┆ ed_ ┆ ipa ┆ lip ┆ ren ┆ --- │
│ --- ┆ t   ┆ --- ┆ str ┆ str ┆ str ┆ nti ┆ u32 ┆ e   ┆ --- ┆ ume ┆ ues ┆ led ┆ tio ┆ t   ┆ ric ┆ pri ┆ --- ┆ pri ┆ qty ┆ tio ┆ pag ┆ cy  ┆ f64 │
│ i32 ┆ --- ┆ str ┆     ┆     ┆     ┆ ty  ┆     ┆ --- ┆ u32 ┆ --- ┆ ted ┆ --- ┆ nal ┆ --- ┆ e   ┆ ce  ┆ f64 ┆ ce  ┆ --- ┆ n_o ┆ e_b ┆ --- ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ u32 ┆     ┆ i64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆     ┆ --- ┆ f64 ┆ ver ┆ ps  ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆     ┆ all ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 65  ┆ med ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 76. ┆ 157 ┆ 156 ┆ 156 ┆ 797 ┆ 76. ┆ 75. ┆ 251 ┆ 3.0 ┆ 332 ┆ 331 ┆ 0.9 ┆ 332 ┆ 0.4 ┆ 0.0 ┆ 7.3 ┆ 181 ┆ 7.1 │
│     ┆ ium ┆ 025 ┆ 5-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 3   ┆ 0   ┆ 515 ┆ 156 ┆ 118 ┆ 3.4 ┆ 6.9 ┆ 936 ┆ 5.8 ┆ 840 ┆ 094 ┆ 643 ┆ .70 ┆ 940 │
│     ┆ _bu ┆ V   ┆ 7-3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 924 ┆ .08 ┆ 31  ┆ 217 ┆ 846 ┆ 31  ┆ 692 ┆ 76  ┆ 71  ┆ 09  ┆ 692 ┆ 33  │
│     ┆ ys  ┆ Com ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 501 ┆     ┆ 39  ┆ 15  ┆     ┆ 09  ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 107 ┆ med ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 50. ┆ 157 ┆ 124 ┆ 124 ┆ 965 ┆ 50. ┆ 39. ┆ 150 ┆ 2.3 ┆ 381 ┆ 382 ┆ 0.7 ┆ 381 ┆ 10. ┆ 0.0 ┆ 11. ┆ 267 ┆ 14. │
│     ┆ ium ┆ 025 ┆ 5-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆ 490 ┆ 714 ┆ 222 ┆ 2.1 ┆ 1.3 ┆ 898 ┆ 6.4 ┆ 509 ┆ 409 ┆ 359 ┆ .17 ┆ 016 │
│     ┆ _bu ┆ V   ┆ 9-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 446 ┆ .51 ┆ 19  ┆ 5   ┆     ┆ 09  ┆ 803 ┆ 554 ┆ 23  ┆ 415 ┆ 103 ┆ 817 │
│     ┆ ys  ┆ Com ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 180 ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ 8   ┆     │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 106 ┆ med ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 52. ┆ 157 ┆ 145 ┆ 145 ┆ 243 ┆ 52. ┆ 48. ┆ 180 ┆ 2.3 ┆ 374 ┆ 376 ┆ 0.9 ┆ 375 ┆ 3.9 ┆ 0.0 ┆ 49. ┆ 985 ┆ 50. │
│     ┆ ium ┆ 025 ┆ 5-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 9   ┆ 0   ┆ 025 ┆ 544 ┆ 935 ┆ 0.7 ┆ 3.7 ┆ 235 ┆ 9.3 ┆ 745 ┆ 196 ┆ 758 ┆ .32 ┆ 654 │
│     ┆ _bu ┆ V   ┆ 9-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 478 ┆ .95 ┆ 36  ┆ 444 ┆ 434 ┆ 67  ┆ 577 ┆ 22  ┆ 91  ┆ 369 ┆ 445 ┆ 482 │
│     ┆ ys  ┆ Com ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 320 ┆     ┆ 44  ┆ 78  ┆     ┆ 79  ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 105 ┆ med ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 54. ┆ 157 ┆ 156 ┆ 156 ┆ 427 ┆ 54. ┆ 53. ┆ 200 ┆ 2.3 ┆ 373 ┆ 374 ┆ 0.9 ┆ 374 ┆ 0.3 ┆ 0.0 ┆ 7.9 ┆ 161 ┆ 7.9 │
│     ┆ ium ┆ 025 ┆ 5-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 4   ┆ 0   ┆ 656 ┆ 831 ┆ 172 ┆ 9.9 ┆ 6.7 ┆ 936 ┆ 2.9 ┆ 439 ┆ 125 ┆ 304 ┆ .47 ┆ 952 │
│     ┆ _bu ┆ V   ┆ 9-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 051 ┆ .19 ┆ 08  ┆ 705 ┆ 428 ┆ 31  ┆ 365 ┆ 49  ┆ 54  ┆ 31  ┆ 091 ┆ 56  │
│     ┆ ys  ┆ Com ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 404 ┆     ┆ 88  ┆ 57  ┆     ┆ 46  ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 104 ┆ med ┆ GC2 ┆ 202 ┆ GC  ┆ buy ┆ 55. ┆ 157 ┆ 156 ┆ 156 ┆ 414 ┆ 55. ┆ 54. ┆ 205 ┆ 2.3 ┆ 377 ┆ 373 ┆ 0.9 ┆ 375 ┆ 0.3 ┆ 0.0 ┆ -53 ┆ -11 ┆ -53 │
│     ┆ ium ┆ 025 ┆ 5-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ 649 ┆ 235 ┆ 145 ┆ 5.6 ┆ 0.8 ┆ 936 ┆ 5.4 ┆ 503 ┆ 132 ┆ .31 ┆ 15. ┆ .73 │
│     ┆ _bu ┆ V   ┆ 9-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 682 ┆ .63 ┆ 76  ┆ 08  ┆ 5   ┆ 31  ┆ 772 ┆ 18  ┆     ┆ 792 ┆ 818 ┆ 338 │
│     ┆ ys  ┆ Com ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 534 ┆     ┆     ┆     ┆     ┆ 44  ┆     ┆     ┆     ┆ 983 ┆     │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 6   ┆ med ┆ PA2 ┆ 202 ┆ PA  ┆ buy ┆ 16. ┆ 157 ┆ 127 ┆ 127 ┆ 194 ┆ 16. ┆ 12. ┆ 271 ┆ 10. ┆ 203 ┆ 213 ┆ 0.8 ┆ 210 ┆ 3.0 ┆ 0.0 ┆ 335 ┆ 120 ┆ 370 │
│     ┆ ium ┆ 022 ┆ 2-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 1   ┆ 0   ┆ 942 ┆ 91. ┆ 053 ┆ 2.8 ┆ 8.2 ┆ 089 ┆ 0.9 ┆ 573 ┆ 066 ┆ .05 ┆ 3.9 ┆ .17 │
│     ┆ _bu ┆ Z   ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 675 ┆ 483 ┆ 829 ┆ 064 ┆ 777 ┆ 17  ┆ 168 ┆ 25  ┆ 68  ┆ 582 ┆ 904 ┆ 494 │
│     ┆ ys  ┆ Com ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 891 ┆     ┆ 52  ┆ 78  ┆     ┆ 16  ┆     ┆     ┆ 7   ┆ 31  ┆ 7   │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 5   ┆ med ┆ PA2 ┆ 202 ┆ PA  ┆ buy ┆ 16. ┆ 157 ┆ 119 ┆ 119 ┆ 128 ┆ 16. ┆ 12. ┆ 243 ┆ 8.8 ┆ 198 ┆ 203 ┆ 0.7 ┆ 200 ┆ 3.8 ┆ 0.0 ┆ 103 ┆ 429 ┆ 135 │
│     ┆ ium ┆ 022 ┆ 2-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 7   ┆ 0   ┆ 127 ┆ 45. ┆ 382 ┆ 6.9 ┆ 3.5 ┆ 579 ┆ 7.4 ┆ 726 ┆ 094 ┆ .47 ┆ .74 ┆ .17 │
│     ┆ _bu ┆ Z   ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 389 ┆ 456 ┆ 48  ┆ 166 ┆     ┆ 62  ┆ 772 ┆ 11  ┆ 23  ┆ 980 ┆ 522 ┆ 968 │
│     ┆ ys  ┆ Com ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 478 ┆     ┆ 67  ┆     ┆     ┆ 41  ┆     ┆     ┆ 3   ┆ 6   ┆ 3   │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆ med ┆ PA2 ┆ 202 ┆ PA  ┆ buy ┆ 16. ┆ 157 ┆ 119 ┆ 119 ┆ 143 ┆ 16. ┆ 12. ┆ 242 ┆ 8.7 ┆ 205 ┆ 198 ┆ 0.7 ┆ 200 ┆ 3.8 ┆ 0.0 ┆ -26 ┆ -94 ┆ -28 │
│     ┆ ium ┆ 022 ┆ 2-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 5   ┆ 0   ┆ 127 ┆ 60. ┆ 864 ┆ 6.0 ┆ 4.7 ┆ 579 ┆ 0.5 ┆ 726 ┆ 084 ┆ 9.9 ┆ 8.8 ┆ 8.4 │
│     ┆ _bu ┆ Z   ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 389 ┆ 940 ┆ 17  ┆     ┆ 5   ┆ 62  ┆ 082 ┆ 11  ┆ 51  ┆ 015 ┆ 936 ┆ 525 │
│     ┆ ys  ┆ Com ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 763 ┆     ┆     ┆     ┆     ┆ 46  ┆     ┆     ┆ 29  ┆ 32  ┆ 88  │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ med ┆ PA2 ┆ 202 ┆ PA  ┆ buy ┆ 15. ┆ 157 ┆ 82  ┆ 82  ┆ 389 ┆ 15. ┆ 7.8 ┆ 158 ┆ 7.1 ┆ 203 ┆ 202 ┆ 0.5 ┆ 201 ┆ 7.1 ┆ 0.0 ┆ -55 ┆ -96 ┆ -31 │
│     ┆ ium ┆ 022 ┆ 2-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 0   ┆ 343 ┆ 19. ┆ 567 ┆ 0.4 ┆ 9.2 ┆ 222 ┆ 9.1 ┆ 656 ┆ 201 ┆ .40 ┆ .58 ┆ .71 │
│     ┆ _bu ┆ Z   ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 95  ┆ 042 ┆ 76  ┆ 285 ┆ 5   ┆ 93  ┆ 785 ┆ 05  ┆ 4   ┆ 694 ┆ 199 ┆ 153 │
│     ┆ ys  ┆ Com ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 434 ┆     ┆ 71  ┆     ┆     ┆ 87  ┆     ┆     ┆ 5   ┆ 8   ┆ 1   │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆ med ┆ PA2 ┆ 202 ┆ PA  ┆ buy ┆ 15. ┆ 157 ┆ 129 ┆ 129 ┆ 121 ┆ 15. ┆ 12. ┆ 249 ┆ 8.9 ┆ 203 ┆ 202 ┆ 0.8 ┆ 202 ┆ 2.6 ┆ 0.0 ┆ -63 ┆ -20 ┆ -68 │
│     ┆ ium ┆ 022 ┆ 2-0 ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 1   ┆ 0   ┆ 324 ┆ 63. ┆ 018 ┆ 8.4 ┆ 0.0 ┆ 216 ┆ 5.4 ┆ 751 ┆ 101 ┆ .61 ┆ 9.1 ┆ .40 │
│     ┆ _bu ┆ Z   ┆ 9-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 841 ┆ 688 ┆ 29  ┆ 444 ┆     ┆ 56  ┆ 775 ┆ 59  ┆ 77  ┆ 164 ┆ 565 ┆ 398 │
│     ┆ ys  ┆ Com ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 437 ┆     ┆ 44  ┆     ┆     ┆ 63  ┆     ┆     ┆ 9   ┆ 74  ┆ 1   │
│     ┆     ┆ dty ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

### Reading the metrics

- **`fill_rate`** = `total_filled / order_quantity`. Baseline TWAP allocates to every bin including zero-volume ones, so illiquid names (e.g. `PA`) under-fill heavily — the gap a smarter schedule should close.
- **`exec_slippage_bps`** — filled-only slippage vs the arrival price, signed so **positive = worse**.
- **`is_bps`** — implementation shortfall vs arrival price, including opportunity cost on the unfilled remainder marked at the day's terminal price. Captures both spread *and* intraday price drift.

To plug in a new strategy, write a function `my_strategy(bins, quantity, **params) -> Sequence[float]` (per-bin requested quantities) and pass `strategy=my_strategy` to `run_strategy` / `run_trade_list`.

## VWAP strategy

The same evaluation, but with `vwap_schedule` — which splits the order across bins **in proportion to each bin's share of the day's traded volume** (`quantity × volume / total_volume`) instead of evenly. It tracks the intraday volume profile (heavy at the open/close, thin midday) and, crucially, allocates **nothing** to zero-volume bins — so it should fill better than TWAP on the illiquid names where naive TWAP wastes quantity on dead bins.

Everything downstream (fill model, metrics) is identical; only the per-bin allocation changes. Run the same bucket so the two are directly comparable.

In [ ]:
# single order, VWAP — same order as the TWAP single-order example above
vwap_fills = run_strategy(day, side=order["side"], quantity=order["quantity"], strategy=vwap_schedule)
summarise_fills(vwap_fills)

In [ ]:
# run the same bucket through VWAP and summarise
vwap_all_fills = run_trade_list(bins, orders, trade_list="medium_buys", strategy=vwap_schedule)
vwap_summary = summarise_fills(vwap_all_fills)
vwap_summary.sort("security", "side")